Eyevinn/intercom-frontend

nginx/nginx.conf
This change allows sharing direct links to production lines when running in a containerized environment.
=> fix: workaround for SPA non-standard HTTP behavior

.env, .gitignore, README.md, src/api/api.ts
When developing locally towards a manager that is running in Open Source Cloud we need to provide the service access token as a bearer token. This change adds the option to set the environment variable VITE_BACKEND_API_KEY with the service access token and also included instructions on how to obtain it.
When application is deployed in the OSC platform this is not needed as authorization is performed using cookies.
=> feat: option to provide bearer token on manager requests

src/components/landing-page/use-fetch-production-list.ts
List is currently displayed wrong and only returns the 10 oldest productions. This is probably due to a re-arrange of the results in handleFetchRequest or somewhere else along the fetch-line.
Added a sorting that guarantees that the sorting always will arrange the production-id from highest to lowest, to make sure that the last added productions will be displayed.
=> fix: list on launch page doesnt display last items

src/components/landing-page/create-production.tsx
Added a button to copy urls to clipboard when a production has successfully been created. The copied information looks like this, because the person copying them won't primarily be using the url:s only distributing them:
test-1: http://<`${window.location.origin}`>/production/139/line/1, test-2: http://<`${window.location.origin}`>/production/139/line/2, test-3: http://<`${window.location.origin}`>/production/139/line/3
=> feat: added copy production-urls to clipboard

src/components/manage-productions/manage-lines.tsx
Ran into a problem where in some cases when adding a line to a production, that line would be added to several productions. The problem seems to stem from the updatedLines-state not being cleared after a successful create or delete.
=> fix: line being added to all prods

src/components/production-line/production-line.tsx
Only show the volume slider on desktop as it currently does not work on mobile, for demo purposes
=> fix: only show volume slider on desktop

src/assets/icons/icon.tsx, src/assets/icons/minus.svg, src/assets/icons/plus.svg, src/components/production-line/production-line.tsx, src/components/volume-slider/volume-slider.tsx
As it was realized we needed to choose to either have volume control on mobile, or keep the possibility to continue to hear the call when mobile was locked, we decided to not have the volume controls on mobile.
=> fix: only keep volume controls on desktop

src/bowser.ts, src/components/production-line/production-line.tsx
Volume control is not supported on iOS mobile and iPhone, so this PR makes sure those features are disabled for those platform. Volume control on Android devices are supported so that is allowed. 
Hotkeys should not show on tablet but they did so I added a check for that as well.
I also noticed some undesired behavior with the volume slider: If you muted the speaker with the button, and then moved the slider, the button made it look like the speaker wasn't muted - but it was. Now I made it so that if the user mutes the speaker with the button, and then moves the slider - the speaker is unmuted.
=> fix: show volume control on supported devices

src/components/landing-page/form-elements.tsx, src/components/production-line/settings-modal.tsx, src/components/remove-button/remove-button.tsx, src/components/verify-decision/verify-decision.tsx
If no disabled-color is added then the button will always use the default green, which is a problem if the button-color is another color than default green.
=> fix: added color for disabled buttons when actionbutton is used

src/components/production-line/production-line.tsx
=> fix: improve pgm line ui

src/components/production-line/minified-user-controls.tsx, src/components/production-line/user-controls.tsx
=> fix: speaker-icon is red when audio-output is 0

src/components/production-line/settings-modal.tsx
=> fix: update form and make warnings and errors work

src/components/header.tsx
The clickable area is now a 'button' instead of a 'div' and spans this area:
=> fix: made the clickable home-area smaller

src/components/production-line/minified-user-controls.tsx, src/components/production-line/production-line.tsx, src/components/production-line/select-devices.tsx, src/components/production-line/user-controls.tsx, src/components/production-list/production-list-item.tsx
Solves bugs:
1. On an audio feed line, if user is set to be the audio feed and changes the input device, the user would be 'reset' to act as listener instead of the audio feed input.
2. When use controls were minimizes, the mute button did not work.
=> fix: audio feed bugs

src/components/calls-page/calls-page.tsx, src/components/calls-page/use-prevent-pull-to-refresh.tsx, src/index.css
Added block that the built in top-scroll refresh is disabled on entire site, to prevent users from being accidentally disconnected from calls.
=> feat: refresh site by top-scroll disabled

src/components/production-line/production-line-components.ts, src/components/production-line/production-line.tsx, src/components/production-line/use-active-participant.tsx
There will be a pulsating background when there is audio-activity on a line that is not a "program output"-line, no pulsation if user is dominant speaker.
Video of the visual effect:
https://github.com/user-attachments/assets/4273b74e-6883-4e19-a6bf-243fb2e8494c
=> feat: added visual feedback when line-activity

src/components/copy-button/copy-all-links-button.tsx, src/components/copy-button/copy-button.tsx, src/components/copy-button/use-copy-links.tsx, src/components/create-production/create-production-page.tsx, src/components/production-line/share-line-link-modal.tsx, src/components/production-list/manage-production-buttons.tsx, src/components/production-list/production-list-components.ts, src/components/production-list/production-list-item.tsx
Moved existing copy-functionality into reusable components and made logic into reusable hook. Updated the copy-button to show icon instead of text that reads "copied"
=> feat: added copy-function to manage-page  and made copy more reusable

src/components/generic-components.ts, src/components/production-line/call-header.tsx, src/components/production-line/production-line-components.ts, src/components/production-list/production-list-components.ts, src/components/production-list/production-list-item.tsx, src/components/user-settings-form/user-settings-form.tsx
Only this slim look on chrome, on firefox the look is the same as with the new fix
=> fix: solved width-issues and mobile-issues on call-view

src/components/generic-components.ts, src/components/production-line/production-line-components.ts, src/components/production-list/production-list-components.ts
=> fix: adjusted width on calls on tablet and laying-down mobile

src/components/copy-button/copy-all-links-button.tsx, src/components/loader/loader.tsx, src/components/production-line/share-line-link-modal.tsx, src/components/refresh-button/refresh-button.tsx, src/components/reload-devices-button.tsx/reload-devices-button.tsx
To fix the issue with users not experiencing that the refresh-link function is re-generating a new link, a delay is added. In the delay-time a spinner is shown and a information-text is added
A spinner is added
On "Create Production"-page
On "Manage Production"-page 
A spinner is added and the url are temporarily switched to the text "Loading..."
=> feat: added a delay to the refresh-link buttons

.husky/commit-msg, .husky/pre-commit, src/components/landing-page/form-elements.tsx, src/components/landing-page/join-production.tsx, src/components/production-line/call-header.tsx, src/components/production-list/production-list-components.ts, src/components/production-list/production-list-item.tsx, src/components/user-settings-form/user-settings-form.tsx
User will select new production from dropdown instead of inserting an id. The current production is preset.
Also removed id from call-header, so it only lists production-name and line-name.
Removed the id from the view on both the landing-page and the manage-page, because we don't specify the IDs anywhere besides in the URLs
=> feat: production list dropdown

src/hooks/use-reauth.tsx
Ignore the 500-error on reauth-fetches, due to being expected when osc-token expires.
=> fix: ignore 500-error on reauth-fetch fail

src/components/production-line/use-line-hotkeys.ts
The last commit solving the issue with the push to talk hotkey introduced a problem where the user was muted if focusing in another window. This PR solves the issue.
=> fix: bug on blur after hotkey fix

src/components/production-line/use-rtc-connection.ts
This PR fixes the issue where sometimes, a WHIP stream in a call did not show as the dominant speaker in the call - instead, a normal user in the call showed as the dominant speaker without talking at all.
=> fix: use whip as dominant speaker

src/assets/icons/icon.tsx, src/assets/icons/warning.svg, src/components/calls-page/connect-to-ws-modal.tsx, src/components/form-elements/form-elements.ts, src/components/production-line/collapsable-section.tsx, src/components/production-line/firefox-warning.tsx, src/components/production-line/select-devices.tsx, src/components/tool-tip/tool-tip.tsx, src/components/tooltip/tooltip.tsx, src/components/user-settings-form/user-settings-form.tsx
Made tooltip into a reusable-component and added a firefox-warning-tooltip. Added the tooltip to all places where devices are set, only showing on firefox.
The tooltip is then shown on hover:
<div align="center">
</div>
=> feat: new firefox device warning

src/components/production-line/production-line.tsx
Don't show the red pulse on the call if there is a WHIP session on that call.
=> fix: no red indicator if whip

src/components/calls-page/connect-to-ws-button.tsx, src/hooks/use-websocket-reconnect.ts, src/hooks/use-websocket.ts
[Related issue](https://github.com/Eyevinn/intercom-frontend/issues/402)
This PR needs to be merged **_before_** the [PR made for companion](https://github.com/Eyevinn/companion-module-eyevinn-intercom/pull/5) for easy and error-free implementation.
**Background:**
As of now, if one is to connect the same companion on multiple browsers, intercom allows for it and causes confusion for the companion. This is not good, since the companion now works for both browsers, and causes the companion to not know exactly which production and line it is in.
**Solution:**
This PR ensures that if one is to connect a companion on multiple browsers, an error shows up, stating that the companion is already connected on another browser and that the user should disconnect before reconnecting. This will only …
=> Show block for connecting multiple companions
